version: '3.8'

services:
  # uft_database:
  #   image: mysql:8.0
  #   container_name: uft_database
  #   restart: always
  #   environment:
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     - uft_network
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20

  uft_backend:
    build: ./Backend 
    container_name: uft_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTE: ${ACCESS_TOKEN_EXPIRE_MINUTE}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    # depends_on:
    #   uft_database:
    #     condition: service_healthy
    volumes:
       - ./media:/media  
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-delay 1
    networks:
      - uft_network
  
  # uft_frontend:
  #   build: ./Frontend
  #   container_name: uft_frontend
  #   restart: always
  #   command: ["npm", "run", "dev", "--", "--host", "--port=4173"]
  #   ports:
  #     - "4173:4173"
  #   volumes:
  #     - ./Frontend:/app
  #     - /app/node_modules
  #   depends_on:
  #     - uft_backend
  #   networks:
  #     - uft_network

  uft_proxy:
    image: nginx:latest
    container_name: utf_nginx
    ports:
      - "80:80"              
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    #   - uft_frontend
      - uft_backend
    networks:
      - uft_network

# volumes:
#   mysql_data:

networks:
  uft_network:
    driver: bridge