services:
  backend:
    build:
      context: ./Backend
    container_name: uft_backend
    env_file:
      - ./.env
    environment:
      APP_ENV: production
      DEBUG: "false"
      STORAGE_DIR: /app/storage
      MODULE_STORAGE_DIR: /app/storage/modules
      PUBLIC_FILE_BASE_URL: /static/modules
    volumes:
      - backend_storage:/app/storage
    expose:
      - "8000"
    restart: unless-stopped
    networks:
      - caddy_net

  frontend:
    build:
      context: ./frontend
    container_name: uft_frontend
    env_file:
      - path: ./frontend/.env
        required: false
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - caddy_net

volumes:
  backend_storage:

networks:
  caddy_net:
    external: true