"""expand_token_id_to_text

Revision ID: d41f55293d3c
Revises: a1b2c3d4e5f6
Create Date: 2026-09-06 15:11:43.007325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd41f55293d3c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_hr_aspirasi_riwayat_id'), 'hr_aspirasi_riwayat', ['id'], unique=False)
    op.alter_column('hr_audit_log', 'via_ai',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('hr_gemini_api_key', sa.Column('urutan_prioritas', sa.Integer(), nullable=False))
    op.add_column('hr_gemini_api_key', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('hr_gemini_api_key', sa.Column('last_error_at', sa.DateTime(), nullable=True))
    op.add_column('hr_gemini_api_key', sa.Column('last_error_reason', sa.Text(), nullable=True))
    op.add_column('hr_gemini_api_key', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('hr_gemini_api_key', 'label',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('hr_gemini_api_key', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_constraint(op.f('hr_gemini_api_key_created_by_fkey'), 'hr_gemini_api_key', type_='foreignkey')
    op.drop_column('hr_gemini_api_key', 'last_used_at')
    op.drop_column('hr_gemini_api_key', 'created_by')
    op.drop_column('hr_gemini_api_key', 'priority')
    op.drop_column('hr_gemini_model_setting', 'is_active')
    op.add_column('hr_medpart_sebar', sa.Column('kontak_wa', sa.String(length=50), nullable=True))
    op.add_column('hr_medpart_sebar', sa.Column('pic', sa.String(length=255), nullable=True))
    op.add_column('hr_medpart_sebar', sa.Column('bisa_bayar', sa.Boolean(), nullable=True))
    op.add_column('hr_medpart_sebar', sa.Column('nominal_bayar', sa.String(length=255), nullable=True))
    op.add_column('hr_medpart_sebar', sa.Column('minimal_follow', sa.Integer(), nullable=True))
    op.drop_column('hr_medpart_sebar', 'syarat_detail')
    op.drop_column('hr_medpart_sebar', 'syarat_berbayar')
    op.drop_column('hr_medpart_sebar', 'harga')
    op.drop_column('hr_medpart_sebar', 'link_akun')
    op.drop_column('hr_medpart_sebar', 'kontak')
    op.drop_column('hr_medpart_sebar', 'jumlah_followers')
    op.drop_column('hr_proker', 'status')
    op.drop_column('hr_proker', 'tanggal_selesai')
    op.drop_column('hr_proker', 'tanggal_mulai')
    op.add_column('hr_proker_medpart', sa.Column('medpart_id', sa.Integer(), nullable=False))
    op.add_column('hr_proker_medpart', sa.Column('status_kehadiran', sa.String(length=50), nullable=True))
    op.add_column('hr_proker_medpart', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('hr_proker_medpart_medpart_masuk_id_fkey'), 'hr_proker_medpart', type_='foreignkey')
    op.create_foreign_key(None, 'hr_proker_medpart', 'hr_medpart_masuk', ['medpart_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hr_proker_medpart', 'id')
    op.drop_column('hr_proker_medpart', 'medpart_masuk_id')
    op.add_column('hr_proker_sponsor', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('hr_proker_sponsor', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.drop_column('hr_proker_sponsor', 'id')
    op.alter_column('hr_reminder', 'jenis',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('hr_reminder', 'judul',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('hr_template_chat', 'kategori',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.add_column('hr_undangan', sa.Column('nama_acara', sa.String(length=255), nullable=False))
    op.add_column('hr_undangan', sa.Column('pengundang', sa.String(length=255), nullable=True))
    op.add_column('hr_undangan', sa.Column('tanggal', sa.DateTime(), nullable=True))
    op.add_column('hr_undangan', sa.Column('lokasi', sa.String(length=500), nullable=True))
    op.drop_column('hr_undangan', 'penyelenggara')
    op.drop_column('hr_undangan', 'judul')
    op.drop_column('hr_undangan', 'deskripsi')
    op.drop_column('hr_undangan', 'tanggal_acara')
    op.drop_column('hr_undangan', 'link_undangan')
    op.add_column('hr_undangan_assignment', sa.Column('akun_id', sa.Integer(), nullable=False))
    op.add_column('hr_undangan_assignment', sa.Column('status_kehadiran', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_hr_undangan_assignment_id'), 'hr_undangan_assignment', ['id'], unique=False)
    op.drop_constraint(op.f('hr_undangan_assignment_user_id_fkey'), 'hr_undangan_assignment', type_='foreignkey')
    op.create_foreign_key(None, 'hr_undangan_assignment', 'akun', ['akun_id'], ['akunID'])
    op.drop_column('hr_undangan_assignment', 'konfirmasi')
    op.drop_column('hr_undangan_assignment', 'user_id')
    op.alter_column('responden', 'tokenID',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_shortlink_slug'), table_name='shortlink')
    op.create_unique_constraint(None, 'shortlink', ['slug'])
    op.alter_column('token', 'tokenID',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'tokenID',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
    op.drop_constraint(None, 'shortlink', type_='unique')
    op.create_index(op.f('ix_shortlink_slug'), 'shortlink', ['slug'], unique=True)
    op.alter_column('responden', 'tokenID',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    op.add_column('hr_undangan_assignment', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hr_undangan_assignment', sa.Column('konfirmasi', sa.VARCHAR(length=50), server_default=sa.text("'Menunggu'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'hr_undangan_assignment', type_='foreignkey')
    op.create_foreign_key(op.f('hr_undangan_assignment_user_id_fkey'), 'hr_undangan_assignment', 'akun', ['user_id'], ['akunID'], ondelete='CASCADE')
    op.drop_index(op.f('ix_hr_undangan_assignment_id'), table_name='hr_undangan_assignment')
    op.drop_column('hr_undangan_assignment', 'status_kehadiran')
    op.drop_column('hr_undangan_assignment', 'akun_id')
    op.add_column('hr_undangan', sa.Column('link_undangan', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hr_undangan', sa.Column('tanggal_acara', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('hr_undangan', sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hr_undangan', sa.Column('judul', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('hr_undangan', sa.Column('penyelenggara', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('hr_undangan', 'lokasi')
    op.drop_column('hr_undangan', 'tanggal')
    op.drop_column('hr_undangan', 'pengundang')
    op.drop_column('hr_undangan', 'nama_acara')
    op.alter_column('hr_template_chat', 'kategori',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('hr_reminder', 'judul',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('hr_reminder', 'jenis',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('hr_proker_sponsor', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('hr_proker_sponsor', 'created_at')
    op.drop_column('hr_proker_sponsor', 'status')
    op.add_column('hr_proker_medpart', sa.Column('medpart_masuk_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hr_proker_medpart', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'hr_proker_medpart', type_='foreignkey')
    op.create_foreign_key(op.f('hr_proker_medpart_medpart_masuk_id_fkey'), 'hr_proker_medpart', 'hr_medpart_masuk', ['medpart_masuk_id'], ['id'], ondelete='CASCADE')
    op.drop_column('hr_proker_medpart', 'created_at')
    op.drop_column('hr_proker_medpart', 'status_kehadiran')
    op.drop_column('hr_proker_medpart', 'medpart_id')
    op.add_column('hr_proker', sa.Column('tanggal_mulai', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('hr_proker', sa.Column('tanggal_selesai', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('hr_proker', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'Perencanaan'::character varying"), autoincrement=False, nullable=False))
    op.add_column('hr_medpart_sebar', sa.Column('jumlah_followers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('hr_medpart_sebar', sa.Column('kontak', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('hr_medpart_sebar', sa.Column('link_akun', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('hr_medpart_sebar', sa.Column('harga', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('hr_medpart_sebar', sa.Column('syarat_berbayar', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('hr_medpart_sebar', sa.Column('syarat_detail', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('hr_medpart_sebar', 'minimal_follow')
    op.drop_column('hr_medpart_sebar', 'nominal_bayar')
    op.drop_column('hr_medpart_sebar', 'bisa_bayar')
    op.drop_column('hr_medpart_sebar', 'pic')
    op.drop_column('hr_medpart_sebar', 'kontak_wa')
    op.add_column('hr_gemini_model_setting', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('hr_gemini_api_key', sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('hr_gemini_api_key', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('hr_gemini_api_key', sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('hr_gemini_api_key_created_by_fkey'), 'hr_gemini_api_key', 'akun', ['created_by'], ['akunID'])
    op.alter_column('hr_gemini_api_key', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('hr_gemini_api_key', 'label',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('hr_gemini_api_key', 'updated_at')
    op.drop_column('hr_gemini_api_key', 'last_error_reason')
    op.drop_column('hr_gemini_api_key', 'last_error_at')
    op.drop_column('hr_gemini_api_key', 'status')
    op.drop_column('hr_gemini_api_key', 'urutan_prioritas')
    op.alter_column('hr_audit_log', 'via_ai',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_hr_aspirasi_riwayat_id'), table_name='hr_aspirasi_riwayat')
    # ### end Alembic commands ###
