events { }

http {
    limit_req_zone $binary_remote_addr zone=addr:10m rate=20r/s;
    server {
        
        listen 80;

        # location / {
        #     limit_req zone=addr burst=20 nodelay;
        #     proxy_pass http://uft_frontend:4173;
        # }

        location /api/ {
            limit_req zone=addr burst=20 nodelay;
            proxy_pass http://uft_backend:8000/;
            proxy_set_header Host $host;
        }
    }
}
